name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/v**
      - next

permissions: {} # Sets all permissions to 'none' by default

jobs:
  release:
    name: "Run semantic release"
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Package
        run: npm run package

      - name: Run semantic release
        run: npx semantic-release --debug --repositoryUrl "$(git remote get-url origin | tr -d '\n')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload Changelog.md
        uses: actions/upload-artifact@v4
        with:
          name: CHANGELOG.md
          path: CHANGELOG.md
